description: >
  Base executor from circle ci
docker:
  - image: 'cimg/base:<<parameters.tag>>'
parameters:
  tag:
    default: edge
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/base/tags
    type: string
